import "./globals.css"
import { UserProvider } from "@auth0/nextjs-auth0/client"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <UserProvider>
                <body className="selection:text-white selection:bg-green-500">{children}</body>
            </UserProvider>
        </html>
    )
}
