import Provider from "~/Providers/ThemeProvider";
import "./globals.css"

export const metadata = {
    title: "Bao Anh's Portfolio",
    description: "Generated by create next app"
}

function RootLayout({ children }) {
    return <>
        <html>
            <body className="bg-white dark:bg-black dark:text-white">
                <Provider>
                    {children}
                </Provider>
            </body>
        </html>
    </>
}

export default RootLayout;