
import Provider from "~/Providers/ThemeProvider";
import "../globals.css"
import NotFound from "../not-found";

export const metadata = {
    title: "Bao Anh's Portfolio",
    description: "Generated by create next app"
}

function RootLayout({ params, children }) {
    const { lang } = params

    if(lang != 'en' && lang != 'vi' && lang) {
        return <NotFound />
    }

    return <>
        <html lang={lang}>
            <body className="bg-white dark:bg-black dark:text-white">
                <Provider>
                    {children}
                </Provider>
            </body>
        </html>
    </>
}

export default RootLayout;